import org.jetbrains.kotlin.gradle.dsl.JvmTarget

plugins {
    id("org.jetbrains.kotlin.multiplatform") version "2.1.0"
    id("com.android.library") version "8.7.0" apply false
    id("maven-publish")
}

group = "io.orch8"
version = providers.environmentVariable("ORCH8_MOBILE_VERSION")
    .orElse(providers.gradleProperty("VERSION_NAME"))
    .orElse("0.0.0-local")
    .get()
    .removePrefix("v")

val orch8MobileVersion = version.toString()

// Targets are selectable so hosts without an Android SDK (or without macOS
// for iOS) can still compile and run the common tests on the JVM target.
val enabledTargets: Set<String> = providers.gradleProperty("orch8.kmp.targets")
    .orElse("android,ios,jvm")
    .get()
    .split(',')
    .map { it.trim().lowercase() }
    .filter { it.isNotEmpty() }
    .toSet()
val androidEnabled = "android" in enabledTargets
val iosEnabled = "ios" in enabledTargets

if (androidEnabled) {
    apply(plugin = "com.android.library")
    extensions.configure<com.android.build.api.dsl.LibraryExtension>("android") {
        namespace = "io.orch8.kmp"
        compileSdk = 35
        defaultConfig { minSdk = 24 }
        compileOptions {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
    }
}

// Sources that bind the common API to the UniFFI-generated Kotlin classes
// (package io.orch8.mobile). They are compiled into both androidMain (against
// the published AAR) and jvmMain (against the checked-in generated bindings),
// so the JVM test run type-checks the adapter against the real binding surface.
val uniffiJvmSources = "src/uniffiJvm/kotlin"

kotlin {
    jvm {
        compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
    }

    if (androidEnabled) {
        androidTarget {
            compilerOptions { jvmTarget.set(JvmTarget.JVM_17) }
            publishLibraryVariants("release")
        }
    }

    if (iosEnabled) {
        listOf(iosX64(), iosArm64(), iosSimulatorArm64()).forEach { target ->
            target.binaries.framework {
                baseName = "Orch8Kmp"
                isStatic = true
            }
        }
    }

    sourceSets {
        commonMain.dependencies {
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.9.0")
            api("org.jetbrains.kotlinx:kotlinx-serialization-json:1.7.3")
        }
        commonTest.dependencies {
            implementation(kotlin("test"))
            implementation("org.jetbrains.kotlinx:kotlinx-coroutines-test:1.9.0")
        }

        jvmMain {
            kotlin.srcDir(uniffiJvmSources)
            // Generated by uniffi-bindgen from orch8-mobile; see
            // orch8-mobile/uniffi.toml ([bindings.kotlin] package_name).
            kotlin.srcDir("../../orch8-mobile/bindings/kotlin")
            dependencies {
                implementation("net.java.dev.jna:jna:5.15.0")
            }
        }

        if (androidEnabled) {
            androidMain {
                kotlin.srcDir(uniffiJvmSources)
                dependencies {
                    implementation("io.orch8:orch8-mobile:$orch8MobileVersion")
                    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-android:1.9.0")
                }
            }
        }
    }
}

publishing {
    publications.withType<MavenPublication>().configureEach {
        pom {
            name.set("Orch8 Kotlin Multiplatform")
            description.set("Coroutine/Flow API for the embedded Orch8 workflow runtime on Android and iOS")
            url.set("https://github.com/orch8-io/engine")
            licenses {
                license {
                    name.set("Business Source License 1.1")
                    url.set("https://github.com/orch8-io/engine/blob/main/LICENSE")
                }
            }
        }
    }
}
