#!/usr/bin/env node
// Generate a docker compose file for the distributed Orch8 benchmark:
// PostgreSQL + one `control` node + N `executor` nodes + W REST workers.
//
//   node gen-compose.mjs --executors=3 --workers=4 --worker-slots=100 --out=compose.yml
//
// Every service gets its own container; pin cpus/memory per service with
// --cpus-per-node / --mem-per-node so a one-machine compose run approximates
// separate hosts (it is still one kernel, one disk, one network namespace —
// see docs/BENCHMARK_DISTRIBUTED.md). Dependency-free; emits YAML by hand.
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const workerScript = fileURLToPath(new URL("../systems/orch8/worker.mjs", import.meta.url));

const args = Object.fromEntries(
  process.argv.slice(2).map((a) => {
    const m = /^--([^=]+)=(.*)$/s.exec(a);
    if (!m) throw new Error(`bad argument ${a} (use --key=value)`);
    return [m[1], m[2]];
  }),
);
const int = (k, d) => {
  const v = args[k] === undefined ? d : Number.parseInt(args[k], 10);
  if (!Number.isInteger(v) || v < 0) throw new Error(`--${k} must be a non-negative integer`);
  return v;
};
const executors = int("executors", 2);
const workers = int("workers", 2);
const slots = int("worker-slots", 100);
const cpus = args["cpus-per-node"] ?? "";
const mem = args["mem-per-node"] ?? "";
const image = args.image ?? "${ORCH8_IMAGE:-ghcr.io/orch8-io/engine:latest}";
const out = args.out ?? "compose.yml";
if (executors < 1) throw new Error("--executors must be >= 1");
if (workers < 1) throw new Error("--workers must be >= 1");

const API_KEY = "bench-only-api-key-not-a-secret-0123456789";
const ENC_KEY = "00112233445566778899aabbccddeeff00112233445566778899aabbccddeeff";
const limits = () =>
  cpus || mem
    ? [
        "    deploy:",
        "      resources:",
        "        limits:",
        ...(cpus ? [`          cpus: "${cpus}"`] : []),
        ...(mem ? [`          memory: ${mem}`] : []),
      ]
    : [];
const engineEnv = (role, migrations) => [
  "    environment:",
  `      ORCH8_NODE_ROLE: ${role}`,
  "      ORCH8_STORAGE_BACKEND: postgres",
  "      ORCH8_DATABASE_URL: postgres://orch8:orch8@postgres:5432/orch8",
  `      ORCH8_RUN_MIGRATIONS: "${migrations}"`,
  "      ORCH8_HTTP_ADDR: 0.0.0.0:8080",
  "      ORCH8_GRPC_ADDR: 0.0.0.0:50051",
  `      ORCH8_API_KEY: ${API_KEY}`,
  `      ORCH8_ENCRYPTION_KEY: ${ENC_KEY}`,
  '      ORCH8_REQUIRE_TENANT_HEADER: "true"',
  "      ORCH8_LOG_LEVEL: warn",
  '      ORCH8_LOG_JSON: "true"',
];
const health = [
  "    healthcheck:",
  '      test: ["CMD", "/usr/local/bin/orch8", "--url", "http://127.0.0.1:8080", "health"]',
  "      interval: 2s",
  "      timeout: 3s",
  "      retries: 60",
];

const lines = [
  `# GENERATED by gen-compose.mjs (executors=${executors}, workers=${workers}, worker_slots=${slots}).`,
  "# Benchmark-only throwaway credentials for a loopback stack; never reuse them.",
  "services:",
  "  postgres:",
  "    image: postgres:16",
  "    environment:",
  "      POSTGRES_DB: orch8",
  "      POSTGRES_USER: orch8",
  "      POSTGRES_PASSWORD: orch8",
  "    healthcheck:",
  '      test: ["CMD-SHELL", "pg_isready -U orch8"]',
  "      interval: 2s",
  "      timeout: 3s",
  "      retries: 30",
  "",
  "  control:",
  `    image: ${image}`,
  '    restart: "no"',
  "    ports:",
  '      - "127.0.0.1:18080:8080"',
  ...engineEnv("control", "true"),
  "    depends_on:",
  "      postgres:",
  "        condition: service_healthy",
  ...health,
  ...limits(),
];
for (let i = 1; i <= executors; i++) {
  lines.push(
    "",
    `  executor-${i}:`,
    `    image: ${image}`,
    '    restart: "no"',
    ...engineEnv("executor", "false"),
    "    depends_on:",
    "      control:",
    "        condition: service_healthy",
    ...health,
    ...limits(),
  );
}
for (let i = 1; i <= workers; i++) {
  lines.push(
    "",
    `  worker-${i}:`,
    "    image: node:22-alpine",
    "    restart: unless-stopped",
    "    working_dir: /bench",
    '    command: ["node", "worker.mjs"]',
    "    environment:",
    "      ORCH8_URL: http://control:8080/api/v1",
    `      ORCH8_API_KEY: ${API_KEY}`,
    "      ORCH8_TENANT_ID: bench",
    `      WORKER_SLOTS: "${slots}"`,
    `      ACTIVITY_LOG: /bench-out/activity-worker-${i}.jsonl`,
    "    volumes:",
    `      - ${workerScript}:/bench/worker.mjs:ro`,
    "      - ${BENCH_OUT_DIR:-./out}:/bench-out",
    "    depends_on:",
    "      control:",
    "        condition: service_healthy",
    ...limits(),
  );
}
writeFileSync(out, `${lines.join("\n")}\n`);
console.log(`wrote ${out}`);
