-- Lease-based cron claims.
--
-- `claim_due_cron_schedules` used to mark a schedule claimed by setting
-- `last_triggered_at = now` and gate claims on
-- `last_triggered_at < next_fire_at`. A failure (or crash) between the claim
-- and `update_cron_fire_times` left `last_triggered_at >= next_fire_at`
-- forever, so the schedule was never claimable again — silently disabled.
--
-- The claim now sets a short `claimed_until` lease instead; advancing the
-- fire times clears it, and an expired lease makes the schedule claimable
-- again. Duplicate fires on re-claim are prevented by the per-fire instance
-- idempotency key (`cron:<id>:<next_fire_at>`).
ALTER TABLE cron_schedules ADD COLUMN IF NOT EXISTS claimed_until TIMESTAMPTZ;
