from typing import Any, Callable, Mapping, Optional, TypeVar, Union, overload

_H = TypeVar("_H", bound=Callable[[dict], Any])

def validate_sequence_json(input: str) -> str: ...
def sequence_schema_version() -> int: ...
def run_sequence_json(
    sequence_json: str, input_json: Optional[str] = None, max_ticks: int = 1000
) -> str: ...

class PermanentError(Exception): ...

class Engine:
    def __init__(self, path: str) -> None: ...
    @classmethod
    def open(cls, path: str) -> Engine: ...
    @property
    def path(self) -> str: ...
    @overload
    def handler(self, name: str) -> Callable[[_H], _H]: ...
    @overload
    def handler(self, name: str, fn: _H) -> _H: ...
    def deploy(self, sequence: Union[Mapping[str, Any], str]) -> str: ...
    def start(
        self,
        name: str,
        input: Optional[Mapping[str, Any]] = None,
        *,
        idempotency_key: Optional[str] = None,
        version: Optional[int] = None,
    ) -> str: ...
    def run(self, id: str, *, timeout: Optional[float] = None) -> dict: ...
    def get(self, id: str) -> dict: ...
    def signal(self, id: str, signal: str, payload: Any = None) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> Engine: ...
    def __exit__(self, *exc: object) -> None: ...
