// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(Orch8MobileFFI)
import Orch8MobileFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_orch8_mobile_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_orch8_mobile_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureOrch8MobileInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.
// Magic number for the Rust proxy to call using the same mechanism as every other method,
// to free the callback once it's dropped by Rust.
private let IDX_CALLBACK_FREE: Int32 = 0
// Callback return codes
private let UNIFFI_CALLBACK_SUCCESS: Int32 = 0
private let UNIFFI_CALLBACK_ERROR: Int32 = 1
private let UNIFFI_CALLBACK_UNEXPECTED_ERROR: Int32 = 2

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt32: FfiConverterPrimitive {
    typealias FfiType = Int32
    typealias SwiftType = Int32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int32, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




/**
 * Callback interface for engine lifecycle events.
 * The host app receives notifications when instances complete, fail, or have pending steps.
 */
public protocol EngineListener: AnyObject, Sendable {
    
    func onInstanceCompleted(instanceId: String, output: String) 
    
    func onInstanceFailed(instanceId: String, error: String) 
    
    func onStepPending(instanceId: String, stepName: String, handler: String) 
    
}
/**
 * Callback interface for engine lifecycle events.
 * The host app receives notifications when instances complete, fail, or have pending steps.
 */
open class EngineListenerImpl: EngineListener, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_orch8_mobile_fn_clone_enginelistener(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_orch8_mobile_fn_free_enginelistener(pointer, $0) }
    }

    

    
open func onInstanceCompleted(instanceId: String, output: String)  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_enginelistener_on_instance_completed(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),
        FfiConverterString.lower(output),$0
    )
}
}
    
open func onInstanceFailed(instanceId: String, error: String)  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_enginelistener_on_instance_failed(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),
        FfiConverterString.lower(error),$0
    )
}
}
    
open func onStepPending(instanceId: String, stepName: String, handler: String)  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_enginelistener_on_step_pending(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),
        FfiConverterString.lower(stepName),
        FfiConverterString.lower(handler),$0
    )
}
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceEngineListener {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceEngineListener] = [UniffiVTableCallbackInterfaceEngineListener(
        onInstanceCompleted: { (
            uniffiHandle: UInt64,
            instanceId: RustBuffer,
            output: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEngineListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onInstanceCompleted(
                     instanceId: try FfiConverterString.lift(instanceId),
                     output: try FfiConverterString.lift(output)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onInstanceFailed: { (
            uniffiHandle: UInt64,
            instanceId: RustBuffer,
            error: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEngineListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onInstanceFailed(
                     instanceId: try FfiConverterString.lift(instanceId),
                     error: try FfiConverterString.lift(error)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        onStepPending: { (
            uniffiHandle: UInt64,
            instanceId: RustBuffer,
            stepName: RustBuffer,
            handler: RustBuffer,
            uniffiOutReturn: UnsafeMutableRawPointer,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> () in
                guard let uniffiObj = try? FfiConverterTypeEngineListener.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return uniffiObj.onStepPending(
                     instanceId: try FfiConverterString.lift(instanceId),
                     stepName: try FfiConverterString.lift(stepName),
                     handler: try FfiConverterString.lift(handler)
                )
            }

            
            let writeReturn = { () }
            uniffiTraitInterfaceCall(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeEngineListener.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface EngineListener: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitEngineListener() {
    uniffi_orch8_mobile_fn_init_callback_vtable_enginelistener(UniffiCallbackInterfaceEngineListener.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeEngineListener: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<EngineListener>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = EngineListener

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> EngineListener {
        return EngineListenerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: EngineListener) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> EngineListener {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: EngineListener, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineListener_lift(_ pointer: UnsafeMutableRawPointer) throws -> EngineListener {
    return try FfiConverterTypeEngineListener.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeEngineListener_lower(_ value: EngineListener) -> UnsafeMutableRawPointer {
    return FfiConverterTypeEngineListener.lower(value)
}






/**
 * The mobile workflow engine. Opaque handle for the host app.
 */
public protocol MobileEngineProtocol: AnyObject, Sendable {
    
    /**
     * List all non-terminal instances.
     */
    func activeInstances() throws  -> [InstanceSummary]
    
    /**
     * Cancel a running instance.
     */
    func cancelInstance(instanceId: String) throws 
    
    /**
     * Complete a step that transitioned to Waiting state (async handler completion).
     * The host app calls this when a long-running UI interaction finishes.
     */
    func completeStep(instanceId: String, stepName: String, output: String) throws 
    
    /**
     * Get the state of a specific instance.
     */
    func getInstance(instanceId: String) throws  -> InstanceState
    
    /**
     * Load a sequence directly from a JSON string, bypassing sync.
     * For development/testing only.
     */
    func loadSequenceFromJson(json: String) throws 
    
    /**
     * List all sequences stored locally.
     */
    func loadedSequences() throws  -> [SequenceInfo]
    
    /**
     * Pause the foreground tick loop. In-flight ticks complete before returning.
     */
    func pause() 
    
    /**
     * Register a native step handler. The handler will be called when a step
     * with the given name is encountered during workflow execution.
     */
    func registerHandler(name: String, handler: StepHandler) 
    
    /**
     * Start a foreground tick loop that runs at the configured interval.
     * Call `pause()` to stop. Safe to call multiple times (idempotent if already running).
     */
    func resume() 
    
    /**
     * Set the event listener for engine lifecycle events.
     */
    func setListener(listener: EngineListener) 
    
    /**
     * Shut down the engine, cancelling all in-flight work.
     */
    func shutdown() 
    
    /**
     * Start a new workflow instance.
     *
     * - `sequence_name`: name of the sequence to run
     * - `input`: JSON string with initial context data
     * - `dedup_key`: optional key to prevent duplicate instances
     *
     * Returns the instance ID.
     */
    func start(sequenceName: String, input: String, dedupKey: String?) throws  -> String
    
    /**
     * Execute a single tick: claim due instances, process steps, handle signals.
     * Returns a summary of what happened. The host app drives the tick cadence.
     */
    func tickOnce() throws  -> TickResult
    
}
/**
 * The mobile workflow engine. Opaque handle for the host app.
 */
open class MobileEngine: MobileEngineProtocol, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_orch8_mobile_fn_clone_mobileengine(self.pointer, $0) }
    }
    /**
     * Create a new mobile engine backed by a `SQLite` database at `db_path`.
     */
public convenience init(dbPath: String, config: MobileEngineConfig)throws  {
    let pointer =
        try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_constructor_mobileengine_new(
        FfiConverterString.lower(dbPath),
        FfiConverterTypeMobileEngineConfig_lower(config),$0
    )
}
    self.init(unsafeFromRawPointer: pointer)
}

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_orch8_mobile_fn_free_mobileengine(pointer, $0) }
    }

    

    
    /**
     * List all non-terminal instances.
     */
open func activeInstances()throws  -> [InstanceSummary]  {
    return try  FfiConverterSequenceTypeInstanceSummary.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_active_instances(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Cancel a running instance.
     */
open func cancelInstance(instanceId: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_cancel_instance(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),$0
    )
}
}
    
    /**
     * Complete a step that transitioned to Waiting state (async handler completion).
     * The host app calls this when a long-running UI interaction finishes.
     */
open func completeStep(instanceId: String, stepName: String, output: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_complete_step(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),
        FfiConverterString.lower(stepName),
        FfiConverterString.lower(output),$0
    )
}
}
    
    /**
     * Get the state of a specific instance.
     */
open func getInstance(instanceId: String)throws  -> InstanceState  {
    return try  FfiConverterTypeInstanceState__lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_get_instance(self.uniffiClonePointer(),
        FfiConverterString.lower(instanceId),$0
    )
})
}
    
    /**
     * Load a sequence directly from a JSON string, bypassing sync.
     * For development/testing only.
     */
open func loadSequenceFromJson(json: String)throws   {try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_load_sequence_from_json(self.uniffiClonePointer(),
        FfiConverterString.lower(json),$0
    )
}
}
    
    /**
     * List all sequences stored locally.
     */
open func loadedSequences()throws  -> [SequenceInfo]  {
    return try  FfiConverterSequenceTypeSequenceInfo.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_loaded_sequences(self.uniffiClonePointer(),$0
    )
})
}
    
    /**
     * Pause the foreground tick loop. In-flight ticks complete before returning.
     */
open func pause()  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_mobileengine_pause(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Register a native step handler. The handler will be called when a step
     * with the given name is encountered during workflow execution.
     */
open func registerHandler(name: String, handler: StepHandler)  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_mobileengine_register_handler(self.uniffiClonePointer(),
        FfiConverterString.lower(name),
        FfiConverterTypeStepHandler_lower(handler),$0
    )
}
}
    
    /**
     * Start a foreground tick loop that runs at the configured interval.
     * Call `pause()` to stop. Safe to call multiple times (idempotent if already running).
     */
open func resume()  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_mobileengine_resume(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Set the event listener for engine lifecycle events.
     */
open func setListener(listener: EngineListener)  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_mobileengine_set_listener(self.uniffiClonePointer(),
        FfiConverterTypeEngineListener_lower(listener),$0
    )
}
}
    
    /**
     * Shut down the engine, cancelling all in-flight work.
     */
open func shutdown()  {try! rustCall() {
    uniffi_orch8_mobile_fn_method_mobileengine_shutdown(self.uniffiClonePointer(),$0
    )
}
}
    
    /**
     * Start a new workflow instance.
     *
     * - `sequence_name`: name of the sequence to run
     * - `input`: JSON string with initial context data
     * - `dedup_key`: optional key to prevent duplicate instances
     *
     * Returns the instance ID.
     */
open func start(sequenceName: String, input: String, dedupKey: String?)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_start(self.uniffiClonePointer(),
        FfiConverterString.lower(sequenceName),
        FfiConverterString.lower(input),
        FfiConverterOptionString.lower(dedupKey),$0
    )
})
}
    
    /**
     * Execute a single tick: claim due instances, process steps, handle signals.
     * Returns a summary of what happened. The host app drives the tick cadence.
     */
open func tickOnce()throws  -> TickResult  {
    return try  FfiConverterTypeTickResult_lift(try rustCallWithError(FfiConverterTypeMobileError_lift) {
    uniffi_orch8_mobile_fn_method_mobileengine_tick_once(self.uniffiClonePointer(),$0
    )
})
}
    

}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileEngine: FfiConverter {

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = MobileEngine

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> MobileEngine {
        return MobileEngine(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: MobileEngine) -> UnsafeMutableRawPointer {
        return value.uniffiClonePointer()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileEngine {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: MobileEngine, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEngine_lift(_ pointer: UnsafeMutableRawPointer) throws -> MobileEngine {
    return try FfiConverterTypeMobileEngine.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEngine_lower(_ value: MobileEngine) -> UnsafeMutableRawPointer {
    return FfiConverterTypeMobileEngine.lower(value)
}






/**
 * Callback interface for host-registered step handlers.
 * Implementations live in Swift/Kotlin and are called by the engine during tick execution.
 */
public protocol StepHandler: AnyObject, Sendable {
    
    func execute(stepName: String, input: String) throws  -> String
    
}
/**
 * Callback interface for host-registered step handlers.
 * Implementations live in Swift/Kotlin and are called by the engine during tick execution.
 */
open class StepHandlerImpl: StepHandler, @unchecked Sendable {
    fileprivate let pointer: UnsafeMutableRawPointer!

    /// Used to instantiate a [FFIObject] without an actual pointer, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoPointer {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromRawPointer pointer: UnsafeMutableRawPointer) {
        self.pointer = pointer
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noPointer: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing [Pointer] the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noPointer: NoPointer) {
        self.pointer = nil
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiClonePointer() -> UnsafeMutableRawPointer {
        return try! rustCall { uniffi_orch8_mobile_fn_clone_stephandler(self.pointer, $0) }
    }
    // No primary constructor declared for this class.

    deinit {
        guard let pointer = pointer else {
            return
        }

        try! rustCall { uniffi_orch8_mobile_fn_free_stephandler(pointer, $0) }
    }

    

    
open func execute(stepName: String, input: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeHandlerError_lift) {
    uniffi_orch8_mobile_fn_method_stephandler_execute(self.uniffiClonePointer(),
        FfiConverterString.lower(stepName),
        FfiConverterString.lower(input),$0
    )
})
}
    

}


// Put the implementation in a struct so we don't pollute the top-level namespace
fileprivate struct UniffiCallbackInterfaceStepHandler {

    // Create the VTable using a series of closures.
    // Swift automatically converts these into C callback functions.
    //
    // This creates 1-element array, since this seems to be the only way to construct a const
    // pointer that we can pass to the Rust code.
    static let vtable: [UniffiVTableCallbackInterfaceStepHandler] = [UniffiVTableCallbackInterfaceStepHandler(
        execute: { (
            uniffiHandle: UInt64,
            stepName: RustBuffer,
            input: RustBuffer,
            uniffiOutReturn: UnsafeMutablePointer<RustBuffer>,
            uniffiCallStatus: UnsafeMutablePointer<RustCallStatus>
        ) in
            let makeCall = {
                () throws -> String in
                guard let uniffiObj = try? FfiConverterTypeStepHandler.handleMap.get(handle: uniffiHandle) else {
                    throw UniffiInternalError.unexpectedStaleHandle
                }
                return try uniffiObj.execute(
                     stepName: try FfiConverterString.lift(stepName),
                     input: try FfiConverterString.lift(input)
                )
            }

            
            let writeReturn = { uniffiOutReturn.pointee = FfiConverterString.lower($0) }
            uniffiTraitInterfaceCallWithError(
                callStatus: uniffiCallStatus,
                makeCall: makeCall,
                writeReturn: writeReturn,
                lowerError: FfiConverterTypeHandlerError_lower
            )
        },
        uniffiFree: { (uniffiHandle: UInt64) -> () in
            let result = try? FfiConverterTypeStepHandler.handleMap.remove(handle: uniffiHandle)
            if result == nil {
                print("Uniffi callback interface StepHandler: handle missing in uniffiFree")
            }
        }
    )]
}

private func uniffiCallbackInitStepHandler() {
    uniffi_orch8_mobile_fn_init_callback_vtable_stephandler(UniffiCallbackInterfaceStepHandler.vtable)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeStepHandler: FfiConverter {
    fileprivate static let handleMap = UniffiHandleMap<StepHandler>()

    typealias FfiType = UnsafeMutableRawPointer
    typealias SwiftType = StepHandler

    public static func lift(_ pointer: UnsafeMutableRawPointer) throws -> StepHandler {
        return StepHandlerImpl(unsafeFromRawPointer: pointer)
    }

    public static func lower(_ value: StepHandler) -> UnsafeMutableRawPointer {
        guard let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: handleMap.insert(obj: value))) else {
            fatalError("Cast to UnsafeMutableRawPointer failed")
        }
        return ptr
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> StepHandler {
        let v: UInt64 = try readInt(&buf)
        // The Rust code won't compile if a pointer won't fit in a UInt64.
        // We have to go via `UInt` because that's the thing that's the size of a pointer.
        let ptr = UnsafeMutableRawPointer(bitPattern: UInt(truncatingIfNeeded: v))
        if (ptr == nil) {
            throw UniffiInternalError.unexpectedNullPointer
        }
        return try lift(ptr!)
    }

    public static func write(_ value: StepHandler, into buf: inout [UInt8]) {
        // This fiddling is because `Int` is the thing that's the same size as a pointer.
        // The Rust code won't compile if a pointer won't fit in a `UInt64`.
        writeInt(&buf, UInt64(bitPattern: Int64(Int(bitPattern: lower(value)))))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStepHandler_lift(_ pointer: UnsafeMutableRawPointer) throws -> StepHandler {
    return try FfiConverterTypeStepHandler.lift(pointer)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeStepHandler_lower(_ value: StepHandler) -> UnsafeMutableRawPointer {
    return FfiConverterTypeStepHandler.lower(value)
}




/**
 * Snapshot of a single instance's state.
 */
public struct InstanceState {
    public let instanceId: String
    public let sequenceName: String
    public let state: String
    public let context: String
    public let createdAt: String
    public let updatedAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(instanceId: String, sequenceName: String, state: String, context: String, createdAt: String, updatedAt: String) {
        self.instanceId = instanceId
        self.sequenceName = sequenceName
        self.state = state
        self.context = context
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

#if compiler(>=6)
extension InstanceState: Sendable {}
#endif


extension InstanceState: Equatable, Hashable {
    public static func ==(lhs: InstanceState, rhs: InstanceState) -> Bool {
        if lhs.instanceId != rhs.instanceId {
            return false
        }
        if lhs.sequenceName != rhs.sequenceName {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.context != rhs.context {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        if lhs.updatedAt != rhs.updatedAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(instanceId)
        hasher.combine(sequenceName)
        hasher.combine(state)
        hasher.combine(context)
        hasher.combine(createdAt)
        hasher.combine(updatedAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInstanceState_: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InstanceState {
        return
            try InstanceState(
                instanceId: FfiConverterString.read(from: &buf), 
                sequenceName: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf), 
                context: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf), 
                updatedAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: InstanceState, into buf: inout [UInt8]) {
        FfiConverterString.write(value.instanceId, into: &buf)
        FfiConverterString.write(value.sequenceName, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.context, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
        FfiConverterString.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceState__lift(_ buf: RustBuffer) throws -> InstanceState {
    return try FfiConverterTypeInstanceState_.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceState__lower(_ value: InstanceState) -> RustBuffer {
    return FfiConverterTypeInstanceState_.lower(value)
}


/**
 * Summary of a running instance, returned by `active_instances()`.
 */
public struct InstanceSummary {
    public let instanceId: String
    public let sequenceName: String
    public let state: String
    public let createdAt: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(instanceId: String, sequenceName: String, state: String, createdAt: String) {
        self.instanceId = instanceId
        self.sequenceName = sequenceName
        self.state = state
        self.createdAt = createdAt
    }
}

#if compiler(>=6)
extension InstanceSummary: Sendable {}
#endif


extension InstanceSummary: Equatable, Hashable {
    public static func ==(lhs: InstanceSummary, rhs: InstanceSummary) -> Bool {
        if lhs.instanceId != rhs.instanceId {
            return false
        }
        if lhs.sequenceName != rhs.sequenceName {
            return false
        }
        if lhs.state != rhs.state {
            return false
        }
        if lhs.createdAt != rhs.createdAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(instanceId)
        hasher.combine(sequenceName)
        hasher.combine(state)
        hasher.combine(createdAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeInstanceSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> InstanceSummary {
        return
            try InstanceSummary(
                instanceId: FfiConverterString.read(from: &buf), 
                sequenceName: FfiConverterString.read(from: &buf), 
                state: FfiConverterString.read(from: &buf), 
                createdAt: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: InstanceSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.instanceId, into: &buf)
        FfiConverterString.write(value.sequenceName, into: &buf)
        FfiConverterString.write(value.state, into: &buf)
        FfiConverterString.write(value.createdAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceSummary_lift(_ buf: RustBuffer) throws -> InstanceSummary {
    return try FfiConverterTypeInstanceSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeInstanceSummary_lower(_ value: InstanceSummary) -> RustBuffer {
    return FfiConverterTypeInstanceSummary.lower(value)
}


/**
 * Configuration for the mobile engine, exposed to host apps via `UniFFI`.
 */
public struct MobileEngineConfig {
    /**
     * Tick interval in milliseconds for the foreground loop (default: 100).
     */
    public let tickIntervalMs: UInt64
    /**
     * Maximum concurrent step executions (default: 4).
     */
    public let maxConcurrentSteps: UInt32
    /**
     * Maximum steps per instance before forced failure (default: 1000).
     */
    public let maxStepsPerInstance: UInt32
    /**
     * Maximum concurrent running instances (default: 10).
     */
    public let maxConcurrentInstances: UInt32
    /**
     * Maximum tick duration in milliseconds before yielding (default: 5000).
     */
    public let maxTickDurationMs: UInt64
    /**
     * Maximum instance lifetime in seconds before auto-cancel (default: 86400 = 24h).
     */
    public let maxInstanceLifetimeSecs: UInt64
    /**
     * Maximum stored sequences in the local database (default: 50).
     */
    public let maxStoredSequences: UInt32
    /**
     * Maximum sequence JSON size in bytes (default: 1MB).
     */
    public let maxSequenceSizeBytes: UInt64
    /**
     * Handler timeout in milliseconds — after this, step transitions to Waiting (default: 30000).
     */
    public let handlerTimeoutMs: UInt64
    /**
     * Enable telemetry collection (default: true).
     */
    public let telemetryEnabled: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Tick interval in milliseconds for the foreground loop (default: 100).
         */tickIntervalMs: UInt64, 
        /**
         * Maximum concurrent step executions (default: 4).
         */maxConcurrentSteps: UInt32, 
        /**
         * Maximum steps per instance before forced failure (default: 1000).
         */maxStepsPerInstance: UInt32, 
        /**
         * Maximum concurrent running instances (default: 10).
         */maxConcurrentInstances: UInt32, 
        /**
         * Maximum tick duration in milliseconds before yielding (default: 5000).
         */maxTickDurationMs: UInt64, 
        /**
         * Maximum instance lifetime in seconds before auto-cancel (default: 86400 = 24h).
         */maxInstanceLifetimeSecs: UInt64, 
        /**
         * Maximum stored sequences in the local database (default: 50).
         */maxStoredSequences: UInt32, 
        /**
         * Maximum sequence JSON size in bytes (default: 1MB).
         */maxSequenceSizeBytes: UInt64, 
        /**
         * Handler timeout in milliseconds — after this, step transitions to Waiting (default: 30000).
         */handlerTimeoutMs: UInt64, 
        /**
         * Enable telemetry collection (default: true).
         */telemetryEnabled: Bool) {
        self.tickIntervalMs = tickIntervalMs
        self.maxConcurrentSteps = maxConcurrentSteps
        self.maxStepsPerInstance = maxStepsPerInstance
        self.maxConcurrentInstances = maxConcurrentInstances
        self.maxTickDurationMs = maxTickDurationMs
        self.maxInstanceLifetimeSecs = maxInstanceLifetimeSecs
        self.maxStoredSequences = maxStoredSequences
        self.maxSequenceSizeBytes = maxSequenceSizeBytes
        self.handlerTimeoutMs = handlerTimeoutMs
        self.telemetryEnabled = telemetryEnabled
    }
}

#if compiler(>=6)
extension MobileEngineConfig: Sendable {}
#endif


extension MobileEngineConfig: Equatable, Hashable {
    public static func ==(lhs: MobileEngineConfig, rhs: MobileEngineConfig) -> Bool {
        if lhs.tickIntervalMs != rhs.tickIntervalMs {
            return false
        }
        if lhs.maxConcurrentSteps != rhs.maxConcurrentSteps {
            return false
        }
        if lhs.maxStepsPerInstance != rhs.maxStepsPerInstance {
            return false
        }
        if lhs.maxConcurrentInstances != rhs.maxConcurrentInstances {
            return false
        }
        if lhs.maxTickDurationMs != rhs.maxTickDurationMs {
            return false
        }
        if lhs.maxInstanceLifetimeSecs != rhs.maxInstanceLifetimeSecs {
            return false
        }
        if lhs.maxStoredSequences != rhs.maxStoredSequences {
            return false
        }
        if lhs.maxSequenceSizeBytes != rhs.maxSequenceSizeBytes {
            return false
        }
        if lhs.handlerTimeoutMs != rhs.handlerTimeoutMs {
            return false
        }
        if lhs.telemetryEnabled != rhs.telemetryEnabled {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(tickIntervalMs)
        hasher.combine(maxConcurrentSteps)
        hasher.combine(maxStepsPerInstance)
        hasher.combine(maxConcurrentInstances)
        hasher.combine(maxTickDurationMs)
        hasher.combine(maxInstanceLifetimeSecs)
        hasher.combine(maxStoredSequences)
        hasher.combine(maxSequenceSizeBytes)
        hasher.combine(handlerTimeoutMs)
        hasher.combine(telemetryEnabled)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileEngineConfig: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileEngineConfig {
        return
            try MobileEngineConfig(
                tickIntervalMs: FfiConverterUInt64.read(from: &buf), 
                maxConcurrentSteps: FfiConverterUInt32.read(from: &buf), 
                maxStepsPerInstance: FfiConverterUInt32.read(from: &buf), 
                maxConcurrentInstances: FfiConverterUInt32.read(from: &buf), 
                maxTickDurationMs: FfiConverterUInt64.read(from: &buf), 
                maxInstanceLifetimeSecs: FfiConverterUInt64.read(from: &buf), 
                maxStoredSequences: FfiConverterUInt32.read(from: &buf), 
                maxSequenceSizeBytes: FfiConverterUInt64.read(from: &buf), 
                handlerTimeoutMs: FfiConverterUInt64.read(from: &buf), 
                telemetryEnabled: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: MobileEngineConfig, into buf: inout [UInt8]) {
        FfiConverterUInt64.write(value.tickIntervalMs, into: &buf)
        FfiConverterUInt32.write(value.maxConcurrentSteps, into: &buf)
        FfiConverterUInt32.write(value.maxStepsPerInstance, into: &buf)
        FfiConverterUInt32.write(value.maxConcurrentInstances, into: &buf)
        FfiConverterUInt64.write(value.maxTickDurationMs, into: &buf)
        FfiConverterUInt64.write(value.maxInstanceLifetimeSecs, into: &buf)
        FfiConverterUInt32.write(value.maxStoredSequences, into: &buf)
        FfiConverterUInt64.write(value.maxSequenceSizeBytes, into: &buf)
        FfiConverterUInt64.write(value.handlerTimeoutMs, into: &buf)
        FfiConverterBool.write(value.telemetryEnabled, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEngineConfig_lift(_ buf: RustBuffer) throws -> MobileEngineConfig {
    return try FfiConverterTypeMobileEngineConfig.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileEngineConfig_lower(_ value: MobileEngineConfig) -> RustBuffer {
    return FfiConverterTypeMobileEngineConfig.lower(value)
}


/**
 * Summary of a stored sequence, returned by `loaded_sequences()`.
 */
public struct SequenceInfo {
    public let name: String
    public let version: Int32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(name: String, version: Int32) {
        self.name = name
        self.version = version
    }
}

#if compiler(>=6)
extension SequenceInfo: Sendable {}
#endif


extension SequenceInfo: Equatable, Hashable {
    public static func ==(lhs: SequenceInfo, rhs: SequenceInfo) -> Bool {
        if lhs.name != rhs.name {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(name)
        hasher.combine(version)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSequenceInfo: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SequenceInfo {
        return
            try SequenceInfo(
                name: FfiConverterString.read(from: &buf), 
                version: FfiConverterInt32.read(from: &buf)
        )
    }

    public static func write(_ value: SequenceInfo, into buf: inout [UInt8]) {
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt32.write(value.version, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSequenceInfo_lift(_ buf: RustBuffer) throws -> SequenceInfo {
    return try FfiConverterTypeSequenceInfo.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSequenceInfo_lower(_ value: SequenceInfo) -> RustBuffer {
    return FfiConverterTypeSequenceInfo.lower(value)
}


/**
 * Result of a single tick execution, returned to the host app.
 */
public struct TickResult {
    public let instancesAdvanced: UInt32
    public let stepsExecuted: UInt32
    public let hasPendingWork: Bool

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(instancesAdvanced: UInt32, stepsExecuted: UInt32, hasPendingWork: Bool) {
        self.instancesAdvanced = instancesAdvanced
        self.stepsExecuted = stepsExecuted
        self.hasPendingWork = hasPendingWork
    }
}

#if compiler(>=6)
extension TickResult: Sendable {}
#endif


extension TickResult: Equatable, Hashable {
    public static func ==(lhs: TickResult, rhs: TickResult) -> Bool {
        if lhs.instancesAdvanced != rhs.instancesAdvanced {
            return false
        }
        if lhs.stepsExecuted != rhs.stepsExecuted {
            return false
        }
        if lhs.hasPendingWork != rhs.hasPendingWork {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(instancesAdvanced)
        hasher.combine(stepsExecuted)
        hasher.combine(hasPendingWork)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTickResult: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TickResult {
        return
            try TickResult(
                instancesAdvanced: FfiConverterUInt32.read(from: &buf), 
                stepsExecuted: FfiConverterUInt32.read(from: &buf), 
                hasPendingWork: FfiConverterBool.read(from: &buf)
        )
    }

    public static func write(_ value: TickResult, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.instancesAdvanced, into: &buf)
        FfiConverterUInt32.write(value.stepsExecuted, into: &buf)
        FfiConverterBool.write(value.hasPendingWork, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTickResult_lift(_ buf: RustBuffer) throws -> TickResult {
    return try FfiConverterTypeTickResult.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTickResult_lower(_ value: TickResult) -> RustBuffer {
    return FfiConverterTypeTickResult.lower(value)
}


/**
 * Handler error returned by host-registered step handlers.
 */
public enum HandlerError: Swift.Error {

    
    
    case Retryable(message: String
    )
    case Permanent(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHandlerError: FfiConverterRustBuffer {
    typealias SwiftType = HandlerError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HandlerError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Retryable(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Permanent(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HandlerError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Retryable(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Permanent(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerError_lift(_ buf: RustBuffer) throws -> HandlerError {
    return try FfiConverterTypeHandlerError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHandlerError_lower(_ value: HandlerError) -> RustBuffer {
    return FfiConverterTypeHandlerError.lower(value)
}


extension HandlerError: Equatable, Hashable {}




extension HandlerError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}





/**
 * Error type exposed to mobile hosts via `UniFFI`.
 */
public enum MobileError: Swift.Error {

    
    
    case Engine(message: String
    )
    case Storage(message: String
    )
    case InvalidInput(message: String
    )
    case NotFound(message: String
    )
    case ResourceLimit(message: String
    )
    case AlreadyExists(message: String
    )
    case Shutdown
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeMobileError: FfiConverterRustBuffer {
    typealias SwiftType = MobileError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> MobileError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Engine(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .Storage(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidInput(
            message: try FfiConverterString.read(from: &buf)
            )
        case 4: return .NotFound(
            message: try FfiConverterString.read(from: &buf)
            )
        case 5: return .ResourceLimit(
            message: try FfiConverterString.read(from: &buf)
            )
        case 6: return .AlreadyExists(
            message: try FfiConverterString.read(from: &buf)
            )
        case 7: return .Shutdown

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: MobileError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Engine(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .Storage(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidInput(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .NotFound(message):
            writeInt(&buf, Int32(4))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .ResourceLimit(message):
            writeInt(&buf, Int32(5))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .AlreadyExists(message):
            writeInt(&buf, Int32(6))
            FfiConverterString.write(message, into: &buf)
            
        
        case .Shutdown:
            writeInt(&buf, Int32(7))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileError_lift(_ buf: RustBuffer) throws -> MobileError {
    return try FfiConverterTypeMobileError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeMobileError_lower(_ value: MobileError) -> RustBuffer {
    return FfiConverterTypeMobileError.lower(value)
}


extension MobileError: Equatable, Hashable {}




extension MobileError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}





/**
 * Sync-specific error type.
 */
public enum SyncError: Swift.Error {

    
    
    case Network(message: String
    )
    case SignatureInvalid(message: String
    )
    case InvalidManifest(message: String
    )
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSyncError: FfiConverterRustBuffer {
    typealias SwiftType = SyncError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SyncError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .Network(
            message: try FfiConverterString.read(from: &buf)
            )
        case 2: return .SignatureInvalid(
            message: try FfiConverterString.read(from: &buf)
            )
        case 3: return .InvalidManifest(
            message: try FfiConverterString.read(from: &buf)
            )

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SyncError, into buf: inout [UInt8]) {
        switch value {

        

        
        
        case let .Network(message):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .SignatureInvalid(message):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(message, into: &buf)
            
        
        case let .InvalidManifest(message):
            writeInt(&buf, Int32(3))
            FfiConverterString.write(message, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncError_lift(_ buf: RustBuffer) throws -> SyncError {
    return try FfiConverterTypeSyncError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSyncError_lower(_ value: SyncError) -> RustBuffer {
    return FfiConverterTypeSyncError.lower(value)
}


extension SyncError: Equatable, Hashable {}




extension SyncError: Foundation.LocalizedError {
    public var errorDescription: String? {
        String(reflecting: self)
    }
}




#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeInstanceSummary: FfiConverterRustBuffer {
    typealias SwiftType = [InstanceSummary]

    public static func write(_ value: [InstanceSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeInstanceSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [InstanceSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [InstanceSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeInstanceSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeSequenceInfo: FfiConverterRustBuffer {
    typealias SwiftType = [SequenceInfo]

    public static func write(_ value: [SequenceInfo], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeSequenceInfo.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [SequenceInfo] {
        let len: Int32 = try readInt(&buf)
        var seq = [SequenceInfo]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeSequenceInfo.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_orch8_mobile_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_enginelistener_on_instance_completed() != 26872) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_enginelistener_on_instance_failed() != 50638) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_enginelistener_on_step_pending() != 29311) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_active_instances() != 45413) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_cancel_instance() != 16979) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_complete_step() != 48470) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_get_instance() != 10545) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_load_sequence_from_json() != 21090) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_loaded_sequences() != 21630) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_pause() != 45793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_register_handler() != 12968) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_resume() != 37038) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_set_listener() != 5960) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_shutdown() != 475) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_start() != 30054) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_mobileengine_tick_once() != 17037) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_method_stephandler_execute() != 2793) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_orch8_mobile_checksum_constructor_mobileengine_new() != 39381) {
        return InitializationResult.apiChecksumMismatch
    }

    uniffiCallbackInitEngineListener()
    uniffiCallbackInitStepHandler()
    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureOrch8MobileInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all